#name: ""
#title: ""

author: Dmitry Rezvanov

header_pages: ['']

ignore_theme_config: true
markdown: kramdown

remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark # if you want it to switch with your system settings.

