author:
  name: Misaka0x2730
  github: "https://github.com/Misaka0x2730"

ignore_theme_config: true
markdown: kramdown

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark # if you want it to switch with your system settings.

