name: Pre-release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: carlosperate/arm-none-eabi-gcc-action@v1

    - name: Update blackmagic
      working-directory: ./firmware/thirdParty/blackmagic
      run: |
        git remote add upstream https://github.com/blackmagic-debug/blackmagic.git
        git fetch upstream
        git checkout main
        git rebase upstream/main

    - name: Update tinyusb
      working-directory: ./firmware/thirdParty/tinyusb
      run: |
        git remote add upstream https://github.com/Misaka0x2730/tinyusb.git
        git fetch upstream
        git checkout rp2040_auto_zlp
        git rebase upstream/master
      
    - name: Configure CMake
      working-directory: ./firmware
      run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ./firmware
      run: cmake --build ./build --config Release

    - name: Rename binary
      working-directory: ./firmware/build
      run: mv MioLink.uf2 MioLink_dev_${{ github.sha }}.uf2

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev"
        prerelease: true
        title: "Development Build"
        files: ./firmware/build/*.uf2
